# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/oskar/dzialajacyprojektxd/tanksgame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/oskar/dzialajacyprojektxd/tanksgame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oskar/dzialajacyprojektxd/tanksgame/CMakeFiles /home/oskar/dzialajacyprojektxd/tanksgame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/oskar/dzialajacyprojektxd/tanksgame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tanksgame

# Build rule for target.
tanksgame: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tanksgame
.PHONY : tanksgame

# fast build rule for target.
tanksgame/fast:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/build
.PHONY : tanksgame/fast

src/Collisions/Collider.o: src/Collisions/Collider.cpp.o

.PHONY : src/Collisions/Collider.o

# target to build an object file
src/Collisions/Collider.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Collider.cpp.o
.PHONY : src/Collisions/Collider.cpp.o

src/Collisions/Collider.i: src/Collisions/Collider.cpp.i

.PHONY : src/Collisions/Collider.i

# target to preprocess a source file
src/Collisions/Collider.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Collider.cpp.i
.PHONY : src/Collisions/Collider.cpp.i

src/Collisions/Collider.s: src/Collisions/Collider.cpp.s

.PHONY : src/Collisions/Collider.s

# target to generate assembly for a file
src/Collisions/Collider.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Collider.cpp.s
.PHONY : src/Collisions/Collider.cpp.s

src/Collisions/Projection.o: src/Collisions/Projection.cpp.o

.PHONY : src/Collisions/Projection.o

# target to build an object file
src/Collisions/Projection.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Projection.cpp.o
.PHONY : src/Collisions/Projection.cpp.o

src/Collisions/Projection.i: src/Collisions/Projection.cpp.i

.PHONY : src/Collisions/Projection.i

# target to preprocess a source file
src/Collisions/Projection.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Projection.cpp.i
.PHONY : src/Collisions/Projection.cpp.i

src/Collisions/Projection.s: src/Collisions/Projection.cpp.s

.PHONY : src/Collisions/Projection.s

# target to generate assembly for a file
src/Collisions/Projection.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Projection.cpp.s
.PHONY : src/Collisions/Projection.cpp.s

src/Collisions/Vector2D.o: src/Collisions/Vector2D.cpp.o

.PHONY : src/Collisions/Vector2D.o

# target to build an object file
src/Collisions/Vector2D.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Vector2D.cpp.o
.PHONY : src/Collisions/Vector2D.cpp.o

src/Collisions/Vector2D.i: src/Collisions/Vector2D.cpp.i

.PHONY : src/Collisions/Vector2D.i

# target to preprocess a source file
src/Collisions/Vector2D.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Vector2D.cpp.i
.PHONY : src/Collisions/Vector2D.cpp.i

src/Collisions/Vector2D.s: src/Collisions/Vector2D.cpp.s

.PHONY : src/Collisions/Vector2D.s

# target to generate assembly for a file
src/Collisions/Vector2D.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Collisions/Vector2D.cpp.s
.PHONY : src/Collisions/Vector2D.cpp.s

src/Configuration.o: src/Configuration.cpp.o

.PHONY : src/Configuration.o

# target to build an object file
src/Configuration.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Configuration.cpp.o
.PHONY : src/Configuration.cpp.o

src/Configuration.i: src/Configuration.cpp.i

.PHONY : src/Configuration.i

# target to preprocess a source file
src/Configuration.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Configuration.cpp.i
.PHONY : src/Configuration.cpp.i

src/Configuration.s: src/Configuration.cpp.s

.PHONY : src/Configuration.s

# target to generate assembly for a file
src/Configuration.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Configuration.cpp.s
.PHONY : src/Configuration.cpp.s

src/Connection/BasePacket.o: src/Connection/BasePacket.cpp.o

.PHONY : src/Connection/BasePacket.o

# target to build an object file
src/Connection/BasePacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BasePacket.cpp.o
.PHONY : src/Connection/BasePacket.cpp.o

src/Connection/BasePacket.i: src/Connection/BasePacket.cpp.i

.PHONY : src/Connection/BasePacket.i

# target to preprocess a source file
src/Connection/BasePacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BasePacket.cpp.i
.PHONY : src/Connection/BasePacket.cpp.i

src/Connection/BasePacket.s: src/Connection/BasePacket.cpp.s

.PHONY : src/Connection/BasePacket.s

# target to generate assembly for a file
src/Connection/BasePacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BasePacket.cpp.s
.PHONY : src/Connection/BasePacket.cpp.s

src/Connection/BulletInfoPacket.o: src/Connection/BulletInfoPacket.cpp.o

.PHONY : src/Connection/BulletInfoPacket.o

# target to build an object file
src/Connection/BulletInfoPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BulletInfoPacket.cpp.o
.PHONY : src/Connection/BulletInfoPacket.cpp.o

src/Connection/BulletInfoPacket.i: src/Connection/BulletInfoPacket.cpp.i

.PHONY : src/Connection/BulletInfoPacket.i

# target to preprocess a source file
src/Connection/BulletInfoPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BulletInfoPacket.cpp.i
.PHONY : src/Connection/BulletInfoPacket.cpp.i

src/Connection/BulletInfoPacket.s: src/Connection/BulletInfoPacket.cpp.s

.PHONY : src/Connection/BulletInfoPacket.s

# target to generate assembly for a file
src/Connection/BulletInfoPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/BulletInfoPacket.cpp.s
.PHONY : src/Connection/BulletInfoPacket.cpp.s

src/Connection/CurrentPositionPacket.o: src/Connection/CurrentPositionPacket.cpp.o

.PHONY : src/Connection/CurrentPositionPacket.o

# target to build an object file
src/Connection/CurrentPositionPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/CurrentPositionPacket.cpp.o
.PHONY : src/Connection/CurrentPositionPacket.cpp.o

src/Connection/CurrentPositionPacket.i: src/Connection/CurrentPositionPacket.cpp.i

.PHONY : src/Connection/CurrentPositionPacket.i

# target to preprocess a source file
src/Connection/CurrentPositionPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/CurrentPositionPacket.cpp.i
.PHONY : src/Connection/CurrentPositionPacket.cpp.i

src/Connection/CurrentPositionPacket.s: src/Connection/CurrentPositionPacket.cpp.s

.PHONY : src/Connection/CurrentPositionPacket.s

# target to generate assembly for a file
src/Connection/CurrentPositionPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/CurrentPositionPacket.cpp.s
.PHONY : src/Connection/CurrentPositionPacket.cpp.s

src/Connection/EventPacket.o: src/Connection/EventPacket.cpp.o

.PHONY : src/Connection/EventPacket.o

# target to build an object file
src/Connection/EventPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/EventPacket.cpp.o
.PHONY : src/Connection/EventPacket.cpp.o

src/Connection/EventPacket.i: src/Connection/EventPacket.cpp.i

.PHONY : src/Connection/EventPacket.i

# target to preprocess a source file
src/Connection/EventPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/EventPacket.cpp.i
.PHONY : src/Connection/EventPacket.cpp.i

src/Connection/EventPacket.s: src/Connection/EventPacket.cpp.s

.PHONY : src/Connection/EventPacket.s

# target to generate assembly for a file
src/Connection/EventPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/EventPacket.cpp.s
.PHONY : src/Connection/EventPacket.cpp.s

src/Connection/HeartbeatPacket.o: src/Connection/HeartbeatPacket.cpp.o

.PHONY : src/Connection/HeartbeatPacket.o

# target to build an object file
src/Connection/HeartbeatPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/HeartbeatPacket.cpp.o
.PHONY : src/Connection/HeartbeatPacket.cpp.o

src/Connection/HeartbeatPacket.i: src/Connection/HeartbeatPacket.cpp.i

.PHONY : src/Connection/HeartbeatPacket.i

# target to preprocess a source file
src/Connection/HeartbeatPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/HeartbeatPacket.cpp.i
.PHONY : src/Connection/HeartbeatPacket.cpp.i

src/Connection/HeartbeatPacket.s: src/Connection/HeartbeatPacket.cpp.s

.PHONY : src/Connection/HeartbeatPacket.s

# target to generate assembly for a file
src/Connection/HeartbeatPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/HeartbeatPacket.cpp.s
.PHONY : src/Connection/HeartbeatPacket.cpp.s

src/Connection/InfoRequestPacket.o: src/Connection/InfoRequestPacket.cpp.o

.PHONY : src/Connection/InfoRequestPacket.o

# target to build an object file
src/Connection/InfoRequestPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/InfoRequestPacket.cpp.o
.PHONY : src/Connection/InfoRequestPacket.cpp.o

src/Connection/InfoRequestPacket.i: src/Connection/InfoRequestPacket.cpp.i

.PHONY : src/Connection/InfoRequestPacket.i

# target to preprocess a source file
src/Connection/InfoRequestPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/InfoRequestPacket.cpp.i
.PHONY : src/Connection/InfoRequestPacket.cpp.i

src/Connection/InfoRequestPacket.s: src/Connection/InfoRequestPacket.cpp.s

.PHONY : src/Connection/InfoRequestPacket.s

# target to generate assembly for a file
src/Connection/InfoRequestPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/InfoRequestPacket.cpp.s
.PHONY : src/Connection/InfoRequestPacket.cpp.s

src/Connection/JoinRequestPacket.o: src/Connection/JoinRequestPacket.cpp.o

.PHONY : src/Connection/JoinRequestPacket.o

# target to build an object file
src/Connection/JoinRequestPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinRequestPacket.cpp.o
.PHONY : src/Connection/JoinRequestPacket.cpp.o

src/Connection/JoinRequestPacket.i: src/Connection/JoinRequestPacket.cpp.i

.PHONY : src/Connection/JoinRequestPacket.i

# target to preprocess a source file
src/Connection/JoinRequestPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinRequestPacket.cpp.i
.PHONY : src/Connection/JoinRequestPacket.cpp.i

src/Connection/JoinRequestPacket.s: src/Connection/JoinRequestPacket.cpp.s

.PHONY : src/Connection/JoinRequestPacket.s

# target to generate assembly for a file
src/Connection/JoinRequestPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinRequestPacket.cpp.s
.PHONY : src/Connection/JoinRequestPacket.cpp.s

src/Connection/JoinResponsePacket.o: src/Connection/JoinResponsePacket.cpp.o

.PHONY : src/Connection/JoinResponsePacket.o

# target to build an object file
src/Connection/JoinResponsePacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinResponsePacket.cpp.o
.PHONY : src/Connection/JoinResponsePacket.cpp.o

src/Connection/JoinResponsePacket.i: src/Connection/JoinResponsePacket.cpp.i

.PHONY : src/Connection/JoinResponsePacket.i

# target to preprocess a source file
src/Connection/JoinResponsePacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinResponsePacket.cpp.i
.PHONY : src/Connection/JoinResponsePacket.cpp.i

src/Connection/JoinResponsePacket.s: src/Connection/JoinResponsePacket.cpp.s

.PHONY : src/Connection/JoinResponsePacket.s

# target to generate assembly for a file
src/Connection/JoinResponsePacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/JoinResponsePacket.cpp.s
.PHONY : src/Connection/JoinResponsePacket.cpp.s

src/Connection/LastPlayerSentPacket.o: src/Connection/LastPlayerSentPacket.cpp.o

.PHONY : src/Connection/LastPlayerSentPacket.o

# target to build an object file
src/Connection/LastPlayerSentPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/LastPlayerSentPacket.cpp.o
.PHONY : src/Connection/LastPlayerSentPacket.cpp.o

src/Connection/LastPlayerSentPacket.i: src/Connection/LastPlayerSentPacket.cpp.i

.PHONY : src/Connection/LastPlayerSentPacket.i

# target to preprocess a source file
src/Connection/LastPlayerSentPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/LastPlayerSentPacket.cpp.i
.PHONY : src/Connection/LastPlayerSentPacket.cpp.i

src/Connection/LastPlayerSentPacket.s: src/Connection/LastPlayerSentPacket.cpp.s

.PHONY : src/Connection/LastPlayerSentPacket.s

# target to generate assembly for a file
src/Connection/LastPlayerSentPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/LastPlayerSentPacket.cpp.s
.PHONY : src/Connection/LastPlayerSentPacket.cpp.s

src/Connection/MapDataPacket.o: src/Connection/MapDataPacket.cpp.o

.PHONY : src/Connection/MapDataPacket.o

# target to build an object file
src/Connection/MapDataPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/MapDataPacket.cpp.o
.PHONY : src/Connection/MapDataPacket.cpp.o

src/Connection/MapDataPacket.i: src/Connection/MapDataPacket.cpp.i

.PHONY : src/Connection/MapDataPacket.i

# target to preprocess a source file
src/Connection/MapDataPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/MapDataPacket.cpp.i
.PHONY : src/Connection/MapDataPacket.cpp.i

src/Connection/MapDataPacket.s: src/Connection/MapDataPacket.cpp.s

.PHONY : src/Connection/MapDataPacket.s

# target to generate assembly for a file
src/Connection/MapDataPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/MapDataPacket.cpp.s
.PHONY : src/Connection/MapDataPacket.cpp.s

src/Connection/NetManager.o: src/Connection/NetManager.cpp.o

.PHONY : src/Connection/NetManager.o

# target to build an object file
src/Connection/NetManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetManager.cpp.o
.PHONY : src/Connection/NetManager.cpp.o

src/Connection/NetManager.i: src/Connection/NetManager.cpp.i

.PHONY : src/Connection/NetManager.i

# target to preprocess a source file
src/Connection/NetManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetManager.cpp.i
.PHONY : src/Connection/NetManager.cpp.i

src/Connection/NetManager.s: src/Connection/NetManager.cpp.s

.PHONY : src/Connection/NetManager.s

# target to generate assembly for a file
src/Connection/NetManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetManager.cpp.s
.PHONY : src/Connection/NetManager.cpp.s

src/Connection/NetPlayer.o: src/Connection/NetPlayer.cpp.o

.PHONY : src/Connection/NetPlayer.o

# target to build an object file
src/Connection/NetPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetPlayer.cpp.o
.PHONY : src/Connection/NetPlayer.cpp.o

src/Connection/NetPlayer.i: src/Connection/NetPlayer.cpp.i

.PHONY : src/Connection/NetPlayer.i

# target to preprocess a source file
src/Connection/NetPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetPlayer.cpp.i
.PHONY : src/Connection/NetPlayer.cpp.i

src/Connection/NetPlayer.s: src/Connection/NetPlayer.cpp.s

.PHONY : src/Connection/NetPlayer.s

# target to generate assembly for a file
src/Connection/NetPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/NetPlayer.cpp.s
.PHONY : src/Connection/NetPlayer.cpp.s

src/Connection/PlayerDisconnectedPacket.o: src/Connection/PlayerDisconnectedPacket.cpp.o

.PHONY : src/Connection/PlayerDisconnectedPacket.o

# target to build an object file
src/Connection/PlayerDisconnectedPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerDisconnectedPacket.cpp.o
.PHONY : src/Connection/PlayerDisconnectedPacket.cpp.o

src/Connection/PlayerDisconnectedPacket.i: src/Connection/PlayerDisconnectedPacket.cpp.i

.PHONY : src/Connection/PlayerDisconnectedPacket.i

# target to preprocess a source file
src/Connection/PlayerDisconnectedPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerDisconnectedPacket.cpp.i
.PHONY : src/Connection/PlayerDisconnectedPacket.cpp.i

src/Connection/PlayerDisconnectedPacket.s: src/Connection/PlayerDisconnectedPacket.cpp.s

.PHONY : src/Connection/PlayerDisconnectedPacket.s

# target to generate assembly for a file
src/Connection/PlayerDisconnectedPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerDisconnectedPacket.cpp.s
.PHONY : src/Connection/PlayerDisconnectedPacket.cpp.s

src/Connection/PlayerJoinedPacket.o: src/Connection/PlayerJoinedPacket.cpp.o

.PHONY : src/Connection/PlayerJoinedPacket.o

# target to build an object file
src/Connection/PlayerJoinedPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerJoinedPacket.cpp.o
.PHONY : src/Connection/PlayerJoinedPacket.cpp.o

src/Connection/PlayerJoinedPacket.i: src/Connection/PlayerJoinedPacket.cpp.i

.PHONY : src/Connection/PlayerJoinedPacket.i

# target to preprocess a source file
src/Connection/PlayerJoinedPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerJoinedPacket.cpp.i
.PHONY : src/Connection/PlayerJoinedPacket.cpp.i

src/Connection/PlayerJoinedPacket.s: src/Connection/PlayerJoinedPacket.cpp.s

.PHONY : src/Connection/PlayerJoinedPacket.s

# target to generate assembly for a file
src/Connection/PlayerJoinedPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/PlayerJoinedPacket.cpp.s
.PHONY : src/Connection/PlayerJoinedPacket.cpp.s

src/Connection/SyncPacket.o: src/Connection/SyncPacket.cpp.o

.PHONY : src/Connection/SyncPacket.o

# target to build an object file
src/Connection/SyncPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/SyncPacket.cpp.o
.PHONY : src/Connection/SyncPacket.cpp.o

src/Connection/SyncPacket.i: src/Connection/SyncPacket.cpp.i

.PHONY : src/Connection/SyncPacket.i

# target to preprocess a source file
src/Connection/SyncPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/SyncPacket.cpp.i
.PHONY : src/Connection/SyncPacket.cpp.i

src/Connection/SyncPacket.s: src/Connection/SyncPacket.cpp.s

.PHONY : src/Connection/SyncPacket.s

# target to generate assembly for a file
src/Connection/SyncPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/SyncPacket.cpp.s
.PHONY : src/Connection/SyncPacket.cpp.s

src/Connection/TCPConnection.o: src/Connection/TCPConnection.cpp.o

.PHONY : src/Connection/TCPConnection.o

# target to build an object file
src/Connection/TCPConnection.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/TCPConnection.cpp.o
.PHONY : src/Connection/TCPConnection.cpp.o

src/Connection/TCPConnection.i: src/Connection/TCPConnection.cpp.i

.PHONY : src/Connection/TCPConnection.i

# target to preprocess a source file
src/Connection/TCPConnection.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/TCPConnection.cpp.i
.PHONY : src/Connection/TCPConnection.cpp.i

src/Connection/TCPConnection.s: src/Connection/TCPConnection.cpp.s

.PHONY : src/Connection/TCPConnection.s

# target to generate assembly for a file
src/Connection/TCPConnection.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/TCPConnection.cpp.s
.PHONY : src/Connection/TCPConnection.cpp.s

src/Connection/UDPConnection.o: src/Connection/UDPConnection.cpp.o

.PHONY : src/Connection/UDPConnection.o

# target to build an object file
src/Connection/UDPConnection.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UDPConnection.cpp.o
.PHONY : src/Connection/UDPConnection.cpp.o

src/Connection/UDPConnection.i: src/Connection/UDPConnection.cpp.i

.PHONY : src/Connection/UDPConnection.i

# target to preprocess a source file
src/Connection/UDPConnection.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UDPConnection.cpp.i
.PHONY : src/Connection/UDPConnection.cpp.i

src/Connection/UDPConnection.s: src/Connection/UDPConnection.cpp.s

.PHONY : src/Connection/UDPConnection.s

# target to generate assembly for a file
src/Connection/UDPConnection.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UDPConnection.cpp.s
.PHONY : src/Connection/UDPConnection.cpp.s

src/Connection/UniversalPacket.o: src/Connection/UniversalPacket.cpp.o

.PHONY : src/Connection/UniversalPacket.o

# target to build an object file
src/Connection/UniversalPacket.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UniversalPacket.cpp.o
.PHONY : src/Connection/UniversalPacket.cpp.o

src/Connection/UniversalPacket.i: src/Connection/UniversalPacket.cpp.i

.PHONY : src/Connection/UniversalPacket.i

# target to preprocess a source file
src/Connection/UniversalPacket.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UniversalPacket.cpp.i
.PHONY : src/Connection/UniversalPacket.cpp.i

src/Connection/UniversalPacket.s: src/Connection/UniversalPacket.cpp.s

.PHONY : src/Connection/UniversalPacket.s

# target to generate assembly for a file
src/Connection/UniversalPacket.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Connection/UniversalPacket.cpp.s
.PHONY : src/Connection/UniversalPacket.cpp.s

src/GUIElement/Button.o: src/GUIElement/Button.cpp.o

.PHONY : src/GUIElement/Button.o

# target to build an object file
src/GUIElement/Button.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/Button.cpp.o
.PHONY : src/GUIElement/Button.cpp.o

src/GUIElement/Button.i: src/GUIElement/Button.cpp.i

.PHONY : src/GUIElement/Button.i

# target to preprocess a source file
src/GUIElement/Button.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/Button.cpp.i
.PHONY : src/GUIElement/Button.cpp.i

src/GUIElement/Button.s: src/GUIElement/Button.cpp.s

.PHONY : src/GUIElement/Button.s

# target to generate assembly for a file
src/GUIElement/Button.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/Button.cpp.s
.PHONY : src/GUIElement/Button.cpp.s

src/GUIElement/TextStatic.o: src/GUIElement/TextStatic.cpp.o

.PHONY : src/GUIElement/TextStatic.o

# target to build an object file
src/GUIElement/TextStatic.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/TextStatic.cpp.o
.PHONY : src/GUIElement/TextStatic.cpp.o

src/GUIElement/TextStatic.i: src/GUIElement/TextStatic.cpp.i

.PHONY : src/GUIElement/TextStatic.i

# target to preprocess a source file
src/GUIElement/TextStatic.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/TextStatic.cpp.i
.PHONY : src/GUIElement/TextStatic.cpp.i

src/GUIElement/TextStatic.s: src/GUIElement/TextStatic.cpp.s

.PHONY : src/GUIElement/TextStatic.s

# target to generate assembly for a file
src/GUIElement/TextStatic.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/TextStatic.cpp.s
.PHONY : src/GUIElement/TextStatic.cpp.s

src/GUIElement/_Element.o: src/GUIElement/_Element.cpp.o

.PHONY : src/GUIElement/_Element.o

# target to build an object file
src/GUIElement/_Element.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/_Element.cpp.o
.PHONY : src/GUIElement/_Element.cpp.o

src/GUIElement/_Element.i: src/GUIElement/_Element.cpp.i

.PHONY : src/GUIElement/_Element.i

# target to preprocess a source file
src/GUIElement/_Element.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/_Element.cpp.i
.PHONY : src/GUIElement/_Element.cpp.i

src/GUIElement/_Element.s: src/GUIElement/_Element.cpp.s

.PHONY : src/GUIElement/_Element.s

# target to generate assembly for a file
src/GUIElement/_Element.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GUIElement/_Element.cpp.s
.PHONY : src/GUIElement/_Element.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameObject/Bullet.o: src/GameObject/Bullet.cpp.o

.PHONY : src/GameObject/Bullet.o

# target to build an object file
src/GameObject/Bullet.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Bullet.cpp.o
.PHONY : src/GameObject/Bullet.cpp.o

src/GameObject/Bullet.i: src/GameObject/Bullet.cpp.i

.PHONY : src/GameObject/Bullet.i

# target to preprocess a source file
src/GameObject/Bullet.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Bullet.cpp.i
.PHONY : src/GameObject/Bullet.cpp.i

src/GameObject/Bullet.s: src/GameObject/Bullet.cpp.s

.PHONY : src/GameObject/Bullet.s

# target to generate assembly for a file
src/GameObject/Bullet.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Bullet.cpp.s
.PHONY : src/GameObject/Bullet.cpp.s

src/GameObject/Player.o: src/GameObject/Player.cpp.o

.PHONY : src/GameObject/Player.o

# target to build an object file
src/GameObject/Player.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Player.cpp.o
.PHONY : src/GameObject/Player.cpp.o

src/GameObject/Player.i: src/GameObject/Player.cpp.i

.PHONY : src/GameObject/Player.i

# target to preprocess a source file
src/GameObject/Player.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Player.cpp.i
.PHONY : src/GameObject/Player.cpp.i

src/GameObject/Player.s: src/GameObject/Player.cpp.s

.PHONY : src/GameObject/Player.s

# target to generate assembly for a file
src/GameObject/Player.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Player.cpp.s
.PHONY : src/GameObject/Player.cpp.s

src/GameObject/Wall.o: src/GameObject/Wall.cpp.o

.PHONY : src/GameObject/Wall.o

# target to build an object file
src/GameObject/Wall.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Wall.cpp.o
.PHONY : src/GameObject/Wall.cpp.o

src/GameObject/Wall.i: src/GameObject/Wall.cpp.i

.PHONY : src/GameObject/Wall.i

# target to preprocess a source file
src/GameObject/Wall.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Wall.cpp.i
.PHONY : src/GameObject/Wall.cpp.i

src/GameObject/Wall.s: src/GameObject/Wall.cpp.s

.PHONY : src/GameObject/Wall.s

# target to generate assembly for a file
src/GameObject/Wall.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/Wall.cpp.s
.PHONY : src/GameObject/Wall.cpp.s

src/GameObject/_GameObject.o: src/GameObject/_GameObject.cpp.o

.PHONY : src/GameObject/_GameObject.o

# target to build an object file
src/GameObject/_GameObject.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/_GameObject.cpp.o
.PHONY : src/GameObject/_GameObject.cpp.o

src/GameObject/_GameObject.i: src/GameObject/_GameObject.cpp.i

.PHONY : src/GameObject/_GameObject.i

# target to preprocess a source file
src/GameObject/_GameObject.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/_GameObject.cpp.i
.PHONY : src/GameObject/_GameObject.cpp.i

src/GameObject/_GameObject.s: src/GameObject/_GameObject.cpp.s

.PHONY : src/GameObject/_GameObject.s

# target to generate assembly for a file
src/GameObject/_GameObject.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/GameObject/_GameObject.cpp.s
.PHONY : src/GameObject/_GameObject.cpp.s

src/Graphics/Animation.o: src/Graphics/Animation.cpp.o

.PHONY : src/Graphics/Animation.o

# target to build an object file
src/Graphics/Animation.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Animation.cpp.o
.PHONY : src/Graphics/Animation.cpp.o

src/Graphics/Animation.i: src/Graphics/Animation.cpp.i

.PHONY : src/Graphics/Animation.i

# target to preprocess a source file
src/Graphics/Animation.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Animation.cpp.i
.PHONY : src/Graphics/Animation.cpp.i

src/Graphics/Animation.s: src/Graphics/Animation.cpp.s

.PHONY : src/Graphics/Animation.s

# target to generate assembly for a file
src/Graphics/Animation.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Animation.cpp.s
.PHONY : src/Graphics/Animation.cpp.s

src/Graphics/Background.o: src/Graphics/Background.cpp.o

.PHONY : src/Graphics/Background.o

# target to build an object file
src/Graphics/Background.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Background.cpp.o
.PHONY : src/Graphics/Background.cpp.o

src/Graphics/Background.i: src/Graphics/Background.cpp.i

.PHONY : src/Graphics/Background.i

# target to preprocess a source file
src/Graphics/Background.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Background.cpp.i
.PHONY : src/Graphics/Background.cpp.i

src/Graphics/Background.s: src/Graphics/Background.cpp.s

.PHONY : src/Graphics/Background.s

# target to generate assembly for a file
src/Graphics/Background.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Background.cpp.s
.PHONY : src/Graphics/Background.cpp.s

src/Graphics/Debugger.o: src/Graphics/Debugger.cpp.o

.PHONY : src/Graphics/Debugger.o

# target to build an object file
src/Graphics/Debugger.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Debugger.cpp.o
.PHONY : src/Graphics/Debugger.cpp.o

src/Graphics/Debugger.i: src/Graphics/Debugger.cpp.i

.PHONY : src/Graphics/Debugger.i

# target to preprocess a source file
src/Graphics/Debugger.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Debugger.cpp.i
.PHONY : src/Graphics/Debugger.cpp.i

src/Graphics/Debugger.s: src/Graphics/Debugger.cpp.s

.PHONY : src/Graphics/Debugger.s

# target to generate assembly for a file
src/Graphics/Debugger.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Debugger.cpp.s
.PHONY : src/Graphics/Debugger.cpp.s

src/Graphics/Sprite.o: src/Graphics/Sprite.cpp.o

.PHONY : src/Graphics/Sprite.o

# target to build an object file
src/Graphics/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Sprite.cpp.o
.PHONY : src/Graphics/Sprite.cpp.o

src/Graphics/Sprite.i: src/Graphics/Sprite.cpp.i

.PHONY : src/Graphics/Sprite.i

# target to preprocess a source file
src/Graphics/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Sprite.cpp.i
.PHONY : src/Graphics/Sprite.cpp.i

src/Graphics/Sprite.s: src/Graphics/Sprite.cpp.s

.PHONY : src/Graphics/Sprite.s

# target to generate assembly for a file
src/Graphics/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Sprite.cpp.s
.PHONY : src/Graphics/Sprite.cpp.s

src/Graphics/TankSprite.o: src/Graphics/TankSprite.cpp.o

.PHONY : src/Graphics/TankSprite.o

# target to build an object file
src/Graphics/TankSprite.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TankSprite.cpp.o
.PHONY : src/Graphics/TankSprite.cpp.o

src/Graphics/TankSprite.i: src/Graphics/TankSprite.cpp.i

.PHONY : src/Graphics/TankSprite.i

# target to preprocess a source file
src/Graphics/TankSprite.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TankSprite.cpp.i
.PHONY : src/Graphics/TankSprite.cpp.i

src/Graphics/TankSprite.s: src/Graphics/TankSprite.cpp.s

.PHONY : src/Graphics/TankSprite.s

# target to generate assembly for a file
src/Graphics/TankSprite.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TankSprite.cpp.s
.PHONY : src/Graphics/TankSprite.cpp.s

src/Graphics/Texture.o: src/Graphics/Texture.cpp.o

.PHONY : src/Graphics/Texture.o

# target to build an object file
src/Graphics/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Texture.cpp.o
.PHONY : src/Graphics/Texture.cpp.o

src/Graphics/Texture.i: src/Graphics/Texture.cpp.i

.PHONY : src/Graphics/Texture.i

# target to preprocess a source file
src/Graphics/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Texture.cpp.i
.PHONY : src/Graphics/Texture.cpp.i

src/Graphics/Texture.s: src/Graphics/Texture.cpp.s

.PHONY : src/Graphics/Texture.s

# target to generate assembly for a file
src/Graphics/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/Texture.cpp.s
.PHONY : src/Graphics/Texture.cpp.s

src/Graphics/TextureManager.o: src/Graphics/TextureManager.cpp.o

.PHONY : src/Graphics/TextureManager.o

# target to build an object file
src/Graphics/TextureManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TextureManager.cpp.o
.PHONY : src/Graphics/TextureManager.cpp.o

src/Graphics/TextureManager.i: src/Graphics/TextureManager.cpp.i

.PHONY : src/Graphics/TextureManager.i

# target to preprocess a source file
src/Graphics/TextureManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TextureManager.cpp.i
.PHONY : src/Graphics/TextureManager.cpp.i

src/Graphics/TextureManager.s: src/Graphics/TextureManager.cpp.s

.PHONY : src/Graphics/TextureManager.s

# target to generate assembly for a file
src/Graphics/TextureManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Graphics/TextureManager.cpp.s
.PHONY : src/Graphics/TextureManager.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Map.o: src/Map.cpp.o

.PHONY : src/Map.o

# target to build an object file
src/Map.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Map.cpp.o
.PHONY : src/Map.cpp.o

src/Map.i: src/Map.cpp.i

.PHONY : src/Map.i

# target to preprocess a source file
src/Map.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Map.cpp.i
.PHONY : src/Map.cpp.i

src/Map.s: src/Map.cpp.s

.PHONY : src/Map.s

# target to generate assembly for a file
src/Map.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Map.cpp.s
.PHONY : src/Map.cpp.s

src/Scene/MainMenu.o: src/Scene/MainMenu.cpp.o

.PHONY : src/Scene/MainMenu.o

# target to build an object file
src/Scene/MainMenu.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MainMenu.cpp.o
.PHONY : src/Scene/MainMenu.cpp.o

src/Scene/MainMenu.i: src/Scene/MainMenu.cpp.i

.PHONY : src/Scene/MainMenu.i

# target to preprocess a source file
src/Scene/MainMenu.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MainMenu.cpp.i
.PHONY : src/Scene/MainMenu.cpp.i

src/Scene/MainMenu.s: src/Scene/MainMenu.cpp.s

.PHONY : src/Scene/MainMenu.s

# target to generate assembly for a file
src/Scene/MainMenu.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MainMenu.cpp.s
.PHONY : src/Scene/MainMenu.cpp.s

src/Scene/Manager.o: src/Scene/Manager.cpp.o

.PHONY : src/Scene/Manager.o

# target to build an object file
src/Scene/Manager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Manager.cpp.o
.PHONY : src/Scene/Manager.cpp.o

src/Scene/Manager.i: src/Scene/Manager.cpp.i

.PHONY : src/Scene/Manager.i

# target to preprocess a source file
src/Scene/Manager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Manager.cpp.i
.PHONY : src/Scene/Manager.cpp.i

src/Scene/Manager.s: src/Scene/Manager.cpp.s

.PHONY : src/Scene/Manager.s

# target to generate assembly for a file
src/Scene/Manager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Manager.cpp.s
.PHONY : src/Scene/Manager.cpp.s

src/Scene/MpManager.o: src/Scene/MpManager.cpp.o

.PHONY : src/Scene/MpManager.o

# target to build an object file
src/Scene/MpManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MpManager.cpp.o
.PHONY : src/Scene/MpManager.cpp.o

src/Scene/MpManager.i: src/Scene/MpManager.cpp.i

.PHONY : src/Scene/MpManager.i

# target to preprocess a source file
src/Scene/MpManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MpManager.cpp.i
.PHONY : src/Scene/MpManager.cpp.i

src/Scene/MpManager.s: src/Scene/MpManager.cpp.s

.PHONY : src/Scene/MpManager.s

# target to generate assembly for a file
src/Scene/MpManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/MpManager.cpp.s
.PHONY : src/Scene/MpManager.cpp.s

src/Scene/Room.o: src/Scene/Room.cpp.o

.PHONY : src/Scene/Room.o

# target to build an object file
src/Scene/Room.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Room.cpp.o
.PHONY : src/Scene/Room.cpp.o

src/Scene/Room.i: src/Scene/Room.cpp.i

.PHONY : src/Scene/Room.i

# target to preprocess a source file
src/Scene/Room.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Room.cpp.i
.PHONY : src/Scene/Room.cpp.i

src/Scene/Room.s: src/Scene/Room.cpp.s

.PHONY : src/Scene/Room.s

# target to generate assembly for a file
src/Scene/Room.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Room.cpp.s
.PHONY : src/Scene/Room.cpp.s

src/Scene/Settings.o: src/Scene/Settings.cpp.o

.PHONY : src/Scene/Settings.o

# target to build an object file
src/Scene/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Settings.cpp.o
.PHONY : src/Scene/Settings.cpp.o

src/Scene/Settings.i: src/Scene/Settings.cpp.i

.PHONY : src/Scene/Settings.i

# target to preprocess a source file
src/Scene/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Settings.cpp.i
.PHONY : src/Scene/Settings.cpp.i

src/Scene/Settings.s: src/Scene/Settings.cpp.s

.PHONY : src/Scene/Settings.s

# target to generate assembly for a file
src/Scene/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/Settings.cpp.s
.PHONY : src/Scene/Settings.cpp.s

src/Scene/SettingsAudio.o: src/Scene/SettingsAudio.cpp.o

.PHONY : src/Scene/SettingsAudio.o

# target to build an object file
src/Scene/SettingsAudio.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsAudio.cpp.o
.PHONY : src/Scene/SettingsAudio.cpp.o

src/Scene/SettingsAudio.i: src/Scene/SettingsAudio.cpp.i

.PHONY : src/Scene/SettingsAudio.i

# target to preprocess a source file
src/Scene/SettingsAudio.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsAudio.cpp.i
.PHONY : src/Scene/SettingsAudio.cpp.i

src/Scene/SettingsAudio.s: src/Scene/SettingsAudio.cpp.s

.PHONY : src/Scene/SettingsAudio.s

# target to generate assembly for a file
src/Scene/SettingsAudio.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsAudio.cpp.s
.PHONY : src/Scene/SettingsAudio.cpp.s

src/Scene/SettingsController.o: src/Scene/SettingsController.cpp.o

.PHONY : src/Scene/SettingsController.o

# target to build an object file
src/Scene/SettingsController.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsController.cpp.o
.PHONY : src/Scene/SettingsController.cpp.o

src/Scene/SettingsController.i: src/Scene/SettingsController.cpp.i

.PHONY : src/Scene/SettingsController.i

# target to preprocess a source file
src/Scene/SettingsController.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsController.cpp.i
.PHONY : src/Scene/SettingsController.cpp.i

src/Scene/SettingsController.s: src/Scene/SettingsController.cpp.s

.PHONY : src/Scene/SettingsController.s

# target to generate assembly for a file
src/Scene/SettingsController.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsController.cpp.s
.PHONY : src/Scene/SettingsController.cpp.s

src/Scene/SettingsGame.o: src/Scene/SettingsGame.cpp.o

.PHONY : src/Scene/SettingsGame.o

# target to build an object file
src/Scene/SettingsGame.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsGame.cpp.o
.PHONY : src/Scene/SettingsGame.cpp.o

src/Scene/SettingsGame.i: src/Scene/SettingsGame.cpp.i

.PHONY : src/Scene/SettingsGame.i

# target to preprocess a source file
src/Scene/SettingsGame.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsGame.cpp.i
.PHONY : src/Scene/SettingsGame.cpp.i

src/Scene/SettingsGame.s: src/Scene/SettingsGame.cpp.s

.PHONY : src/Scene/SettingsGame.s

# target to generate assembly for a file
src/Scene/SettingsGame.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsGame.cpp.s
.PHONY : src/Scene/SettingsGame.cpp.s

src/Scene/SettingsVideo.o: src/Scene/SettingsVideo.cpp.o

.PHONY : src/Scene/SettingsVideo.o

# target to build an object file
src/Scene/SettingsVideo.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsVideo.cpp.o
.PHONY : src/Scene/SettingsVideo.cpp.o

src/Scene/SettingsVideo.i: src/Scene/SettingsVideo.cpp.i

.PHONY : src/Scene/SettingsVideo.i

# target to preprocess a source file
src/Scene/SettingsVideo.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsVideo.cpp.i
.PHONY : src/Scene/SettingsVideo.cpp.i

src/Scene/SettingsVideo.s: src/Scene/SettingsVideo.cpp.s

.PHONY : src/Scene/SettingsVideo.s

# target to generate assembly for a file
src/Scene/SettingsVideo.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/SettingsVideo.cpp.s
.PHONY : src/Scene/SettingsVideo.cpp.s

src/Scene/_Menu.o: src/Scene/_Menu.cpp.o

.PHONY : src/Scene/_Menu.o

# target to build an object file
src/Scene/_Menu.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Menu.cpp.o
.PHONY : src/Scene/_Menu.cpp.o

src/Scene/_Menu.i: src/Scene/_Menu.cpp.i

.PHONY : src/Scene/_Menu.i

# target to preprocess a source file
src/Scene/_Menu.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Menu.cpp.i
.PHONY : src/Scene/_Menu.cpp.i

src/Scene/_Menu.s: src/Scene/_Menu.cpp.s

.PHONY : src/Scene/_Menu.s

# target to generate assembly for a file
src/Scene/_Menu.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Menu.cpp.s
.PHONY : src/Scene/_Menu.cpp.s

src/Scene/_Scene.o: src/Scene/_Scene.cpp.o

.PHONY : src/Scene/_Scene.o

# target to build an object file
src/Scene/_Scene.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Scene.cpp.o
.PHONY : src/Scene/_Scene.cpp.o

src/Scene/_Scene.i: src/Scene/_Scene.cpp.i

.PHONY : src/Scene/_Scene.i

# target to preprocess a source file
src/Scene/_Scene.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Scene.cpp.i
.PHONY : src/Scene/_Scene.cpp.i

src/Scene/_Scene.s: src/Scene/_Scene.cpp.s

.PHONY : src/Scene/_Scene.s

# target to generate assembly for a file
src/Scene/_Scene.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Scene/_Scene.cpp.s
.PHONY : src/Scene/_Scene.cpp.s

src/SoundManager.o: src/SoundManager.cpp.o

.PHONY : src/SoundManager.o

# target to build an object file
src/SoundManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/SoundManager.cpp.o
.PHONY : src/SoundManager.cpp.o

src/SoundManager.i: src/SoundManager.cpp.i

.PHONY : src/SoundManager.i

# target to preprocess a source file
src/SoundManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/SoundManager.cpp.i
.PHONY : src/SoundManager.cpp.i

src/SoundManager.s: src/SoundManager.cpp.s

.PHONY : src/SoundManager.s

# target to generate assembly for a file
src/SoundManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/SoundManager.cpp.s
.PHONY : src/SoundManager.cpp.s

src/Text/Font.o: src/Text/Font.cpp.o

.PHONY : src/Text/Font.o

# target to build an object file
src/Text/Font.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Font.cpp.o
.PHONY : src/Text/Font.cpp.o

src/Text/Font.i: src/Text/Font.cpp.i

.PHONY : src/Text/Font.i

# target to preprocess a source file
src/Text/Font.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Font.cpp.i
.PHONY : src/Text/Font.cpp.i

src/Text/Font.s: src/Text/Font.cpp.s

.PHONY : src/Text/Font.s

# target to generate assembly for a file
src/Text/Font.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Font.cpp.s
.PHONY : src/Text/Font.cpp.s

src/Text/Letter.o: src/Text/Letter.cpp.o

.PHONY : src/Text/Letter.o

# target to build an object file
src/Text/Letter.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Letter.cpp.o
.PHONY : src/Text/Letter.cpp.o

src/Text/Letter.i: src/Text/Letter.cpp.i

.PHONY : src/Text/Letter.i

# target to preprocess a source file
src/Text/Letter.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Letter.cpp.i
.PHONY : src/Text/Letter.cpp.i

src/Text/Letter.s: src/Text/Letter.cpp.s

.PHONY : src/Text/Letter.s

# target to generate assembly for a file
src/Text/Letter.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/Letter.cpp.s
.PHONY : src/Text/Letter.cpp.s

src/Text/TextManager.o: src/Text/TextManager.cpp.o

.PHONY : src/Text/TextManager.o

# target to build an object file
src/Text/TextManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/TextManager.cpp.o
.PHONY : src/Text/TextManager.cpp.o

src/Text/TextManager.i: src/Text/TextManager.cpp.i

.PHONY : src/Text/TextManager.i

# target to preprocess a source file
src/Text/TextManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/TextManager.cpp.i
.PHONY : src/Text/TextManager.cpp.i

src/Text/TextManager.s: src/Text/TextManager.cpp.s

.PHONY : src/Text/TextManager.s

# target to generate assembly for a file
src/Text/TextManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Text/TextManager.cpp.s
.PHONY : src/Text/TextManager.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/WindowManager.o: src/WindowManager.cpp.o

.PHONY : src/WindowManager.o

# target to build an object file
src/WindowManager.cpp.o:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/WindowManager.cpp.o
.PHONY : src/WindowManager.cpp.o

src/WindowManager.i: src/WindowManager.cpp.i

.PHONY : src/WindowManager.i

# target to preprocess a source file
src/WindowManager.cpp.i:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/WindowManager.cpp.i
.PHONY : src/WindowManager.cpp.i

src/WindowManager.s: src/WindowManager.cpp.s

.PHONY : src/WindowManager.s

# target to generate assembly for a file
src/WindowManager.cpp.s:
	$(MAKE) -f CMakeFiles/tanksgame.dir/build.make CMakeFiles/tanksgame.dir/src/WindowManager.cpp.s
.PHONY : src/WindowManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... tanksgame"
	@echo "... edit_cache"
	@echo "... src/Collisions/Collider.o"
	@echo "... src/Collisions/Collider.i"
	@echo "... src/Collisions/Collider.s"
	@echo "... src/Collisions/Projection.o"
	@echo "... src/Collisions/Projection.i"
	@echo "... src/Collisions/Projection.s"
	@echo "... src/Collisions/Vector2D.o"
	@echo "... src/Collisions/Vector2D.i"
	@echo "... src/Collisions/Vector2D.s"
	@echo "... src/Configuration.o"
	@echo "... src/Configuration.i"
	@echo "... src/Configuration.s"
	@echo "... src/Connection/BasePacket.o"
	@echo "... src/Connection/BasePacket.i"
	@echo "... src/Connection/BasePacket.s"
	@echo "... src/Connection/BulletInfoPacket.o"
	@echo "... src/Connection/BulletInfoPacket.i"
	@echo "... src/Connection/BulletInfoPacket.s"
	@echo "... src/Connection/CurrentPositionPacket.o"
	@echo "... src/Connection/CurrentPositionPacket.i"
	@echo "... src/Connection/CurrentPositionPacket.s"
	@echo "... src/Connection/EventPacket.o"
	@echo "... src/Connection/EventPacket.i"
	@echo "... src/Connection/EventPacket.s"
	@echo "... src/Connection/HeartbeatPacket.o"
	@echo "... src/Connection/HeartbeatPacket.i"
	@echo "... src/Connection/HeartbeatPacket.s"
	@echo "... src/Connection/InfoRequestPacket.o"
	@echo "... src/Connection/InfoRequestPacket.i"
	@echo "... src/Connection/InfoRequestPacket.s"
	@echo "... src/Connection/JoinRequestPacket.o"
	@echo "... src/Connection/JoinRequestPacket.i"
	@echo "... src/Connection/JoinRequestPacket.s"
	@echo "... src/Connection/JoinResponsePacket.o"
	@echo "... src/Connection/JoinResponsePacket.i"
	@echo "... src/Connection/JoinResponsePacket.s"
	@echo "... src/Connection/LastPlayerSentPacket.o"
	@echo "... src/Connection/LastPlayerSentPacket.i"
	@echo "... src/Connection/LastPlayerSentPacket.s"
	@echo "... src/Connection/MapDataPacket.o"
	@echo "... src/Connection/MapDataPacket.i"
	@echo "... src/Connection/MapDataPacket.s"
	@echo "... src/Connection/NetManager.o"
	@echo "... src/Connection/NetManager.i"
	@echo "... src/Connection/NetManager.s"
	@echo "... src/Connection/NetPlayer.o"
	@echo "... src/Connection/NetPlayer.i"
	@echo "... src/Connection/NetPlayer.s"
	@echo "... src/Connection/PlayerDisconnectedPacket.o"
	@echo "... src/Connection/PlayerDisconnectedPacket.i"
	@echo "... src/Connection/PlayerDisconnectedPacket.s"
	@echo "... src/Connection/PlayerJoinedPacket.o"
	@echo "... src/Connection/PlayerJoinedPacket.i"
	@echo "... src/Connection/PlayerJoinedPacket.s"
	@echo "... src/Connection/SyncPacket.o"
	@echo "... src/Connection/SyncPacket.i"
	@echo "... src/Connection/SyncPacket.s"
	@echo "... src/Connection/TCPConnection.o"
	@echo "... src/Connection/TCPConnection.i"
	@echo "... src/Connection/TCPConnection.s"
	@echo "... src/Connection/UDPConnection.o"
	@echo "... src/Connection/UDPConnection.i"
	@echo "... src/Connection/UDPConnection.s"
	@echo "... src/Connection/UniversalPacket.o"
	@echo "... src/Connection/UniversalPacket.i"
	@echo "... src/Connection/UniversalPacket.s"
	@echo "... src/GUIElement/Button.o"
	@echo "... src/GUIElement/Button.i"
	@echo "... src/GUIElement/Button.s"
	@echo "... src/GUIElement/TextStatic.o"
	@echo "... src/GUIElement/TextStatic.i"
	@echo "... src/GUIElement/TextStatic.s"
	@echo "... src/GUIElement/_Element.o"
	@echo "... src/GUIElement/_Element.i"
	@echo "... src/GUIElement/_Element.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameObject/Bullet.o"
	@echo "... src/GameObject/Bullet.i"
	@echo "... src/GameObject/Bullet.s"
	@echo "... src/GameObject/Player.o"
	@echo "... src/GameObject/Player.i"
	@echo "... src/GameObject/Player.s"
	@echo "... src/GameObject/Wall.o"
	@echo "... src/GameObject/Wall.i"
	@echo "... src/GameObject/Wall.s"
	@echo "... src/GameObject/_GameObject.o"
	@echo "... src/GameObject/_GameObject.i"
	@echo "... src/GameObject/_GameObject.s"
	@echo "... src/Graphics/Animation.o"
	@echo "... src/Graphics/Animation.i"
	@echo "... src/Graphics/Animation.s"
	@echo "... src/Graphics/Background.o"
	@echo "... src/Graphics/Background.i"
	@echo "... src/Graphics/Background.s"
	@echo "... src/Graphics/Debugger.o"
	@echo "... src/Graphics/Debugger.i"
	@echo "... src/Graphics/Debugger.s"
	@echo "... src/Graphics/Sprite.o"
	@echo "... src/Graphics/Sprite.i"
	@echo "... src/Graphics/Sprite.s"
	@echo "... src/Graphics/TankSprite.o"
	@echo "... src/Graphics/TankSprite.i"
	@echo "... src/Graphics/TankSprite.s"
	@echo "... src/Graphics/Texture.o"
	@echo "... src/Graphics/Texture.i"
	@echo "... src/Graphics/Texture.s"
	@echo "... src/Graphics/TextureManager.o"
	@echo "... src/Graphics/TextureManager.i"
	@echo "... src/Graphics/TextureManager.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Map.o"
	@echo "... src/Map.i"
	@echo "... src/Map.s"
	@echo "... src/Scene/MainMenu.o"
	@echo "... src/Scene/MainMenu.i"
	@echo "... src/Scene/MainMenu.s"
	@echo "... src/Scene/Manager.o"
	@echo "... src/Scene/Manager.i"
	@echo "... src/Scene/Manager.s"
	@echo "... src/Scene/MpManager.o"
	@echo "... src/Scene/MpManager.i"
	@echo "... src/Scene/MpManager.s"
	@echo "... src/Scene/Room.o"
	@echo "... src/Scene/Room.i"
	@echo "... src/Scene/Room.s"
	@echo "... src/Scene/Settings.o"
	@echo "... src/Scene/Settings.i"
	@echo "... src/Scene/Settings.s"
	@echo "... src/Scene/SettingsAudio.o"
	@echo "... src/Scene/SettingsAudio.i"
	@echo "... src/Scene/SettingsAudio.s"
	@echo "... src/Scene/SettingsController.o"
	@echo "... src/Scene/SettingsController.i"
	@echo "... src/Scene/SettingsController.s"
	@echo "... src/Scene/SettingsGame.o"
	@echo "... src/Scene/SettingsGame.i"
	@echo "... src/Scene/SettingsGame.s"
	@echo "... src/Scene/SettingsVideo.o"
	@echo "... src/Scene/SettingsVideo.i"
	@echo "... src/Scene/SettingsVideo.s"
	@echo "... src/Scene/_Menu.o"
	@echo "... src/Scene/_Menu.i"
	@echo "... src/Scene/_Menu.s"
	@echo "... src/Scene/_Scene.o"
	@echo "... src/Scene/_Scene.i"
	@echo "... src/Scene/_Scene.s"
	@echo "... src/SoundManager.o"
	@echo "... src/SoundManager.i"
	@echo "... src/SoundManager.s"
	@echo "... src/Text/Font.o"
	@echo "... src/Text/Font.i"
	@echo "... src/Text/Font.s"
	@echo "... src/Text/Letter.o"
	@echo "... src/Text/Letter.i"
	@echo "... src/Text/Letter.s"
	@echo "... src/Text/TextManager.o"
	@echo "... src/Text/TextManager.i"
	@echo "... src/Text/TextManager.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/WindowManager.o"
	@echo "... src/WindowManager.i"
	@echo "... src/WindowManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

